#!/usr/bin/bash

CWD=$(realpath .)
VER=2.35
NAME="ns-$VER"
INSTALL_DIR="bin"

[ -d "$INSTALL_DIR" ] || ( \
	wget -nc "https://downloads.sourceforge.net/project/nsnam/ns-2/2.35/ns-src-2.35.tar.gz" -O $NAME.tgz ; \
	tar xvf $NAME.tgz 2> /dev/null && mv $NAME/$INSTALL_DIR/ $INSTALL_DIR && rm -rf $NAME/
)

for i in $(echo $PATH | tr ':' ' ')
do
	[ "$(echo $i | \grep -E '/home/.*/bin$')" = "$CWD/$INSTALL_DIR" ] && return 0
done

PATH="$PATH:$CWD/$INSTALL_DIR" && return 0
return 1
